<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\K4os.Orleans.Streaming.Redis\K4os.Orleans.Streaming.Redis.csproj" />
  </ItemGroup>
  
  <Import Project="..\..\.paket\Paket.Restore.targets" />
  
</Project>